DROP DATABASE IF EXISTS forum_souleu;
CREATE DATABASE forum_souleu
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE forum_souleu;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pseudo VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    passwd VARCHAR(255) NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE NOT NULL,
    date_inscription TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    jwt TEXT, 
    is_ban BOOLEAN DEFAULT FALSE NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tags (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(50) NOT NULL UNIQUE,
    description TEXT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS fils (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titre VARCHAR(255) NOT NULL,
    statut ENUM('ouvert', 'fermé', 'archivé') DEFAULT 'ouvert' NOT NULL,
    score INT NOT NULL DEFAULT 0, 
    fk_user INT NULL,
    fk_tag INT NULL, 
    
    FOREIGN KEY (fk_user) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE, 
    FOREIGN KEY (fk_tag) REFERENCES tags(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    contenu TEXT NOT NULL,
    date_publication DATETIME DEFAULT CURRENT_TIMESTAMP, 
    fk_user INT NULL,
    fk_fil INT NOT NULL,
    FOREIGN KEY (fk_user) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (fk_fil) REFERENCES fils(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS reactions (
    fk_user INT NOT NULL,
    fk_message INT NOT NULL,
    type_reaction ENUM('like', 'dislike') NOT NULL,
    PRIMARY KEY (fk_user, fk_message),
    FOREIGN KEY (fk_user) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (fk_message) REFERENCES messages(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;